### ISSUE TITLE
Get-Mutex not working across process boundaries

### ISSUE THREAD

**Issue by Callidus2000** [FriedrichWeinmann/Mutex#5]
Hi,
is it possible to check if a mutex is locked by another process?

Usage example scenario: Two powershell command prompts (P1 and P2).

- p1> `Get-Mutex MyMutex #returns nothing, expected behavior`
- p1> `Lock-Mutex MyMutex #returns true, expected behavior`
- p2> `Get-Mutex MyMutex #returns nothing, unexpected behavior`
- p2> `Lock-Mutex MyMutex #halts the process as the mutex is locked by p1`

**Comment by FriedrichWeinmann** [comment]
Heya, unfortunately, I have not found a way to do globally scan for mutexes, sooo ... I thought it wouldn't be possible.
Turns out, that thinking it over on your request triggered something ...

But first things first: At this time, `Get-Mutex` will only return the in-memory cache, so if you haven't created or locked the mutex in that process yet, you have no cache and that's that.

Checking out the type I can do a bit more though:
+ `[System.Threading.Mutex]::TryOpenExisting("foo", [ref]$a)` allows me to check whether it exists from another process
+ Trying to acquire the lock with a real short timeout would tell me whether it is locked somewhere else

Can definitely add that capability to the kit

**Comment by Callidus2000** [comment]
Hi,
added a Test-Mutex function as a wrapper to TryOpenExisting and submitted it in PR8.

**Comment by Callidus2000** [comment]
Modified `Test-Mutex` to enable checking if a mutex has already been locked.

**Comment by FriedrichWeinmann** [comment]
Aye, thank you for the contribution in 1.1.11 - Test-Mutex now exists and covers the points here.
I'll be closing this issue for now as resolved
